# harness.io/skip-file-for-deploy
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  accesskey: "NDc5YWViYzUtMjk3Ny00MGVmLWFiYjItNjg1Njc0ZmJhOTA2"
  accountname: "Y3VzdG9tZXIx"
